name: fluttergameserver
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  broadcast_bloc: ^0.1.0-dev.2
  dart_frog: ^1.0.0
  dart_frog_web_socket: ^1.0.0
  equatable: ^2.0.5
  hive: ^2.2.3 
  hive_flutter: ^1.1.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
